# Teste de Rotas

POST http://localhost:3333/events
Content-Type: application/json

# Corpo da requisição
{
  "title": 123,
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/2a645cbe-3a6d-4de9-ab80-ab140d6ff86e/attendees
Content-Type: application/json

{
  "name": "Ghabriel Molina",
  "email": "ghabrielmolina@hotmail.com"
}

###

GET http://localhost:3333/events/2a645cbe-3a6d-4de9-ab80-ab140d6ff86e

###

GET http://localhost:3333/attendees/2/badge

###

GET http://localhost:3333/attendees/4/check-in

###

GET http://localhost:3333/events/2a645cbe-3a6d-4de9-ab80-ab140d6ff86e/attendees?query=ghabriel